dist: xenial
language: python
cache: pip
services:
- docker
env:
  matrix:
  - version=2.7
  - version=3.5
  - version=3.6
  - version=3.7
  - version=3.8
  global:
  - CC_TEST_REPORTER_ID=$TRAVIS_CODE_CLIMATE_TOKEN
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- make test-docker
after_script:
- make test-install
- ". venv/bin/activate; codecov"
- "./cc-test-reporter after-build --exit-code $?"
deploy:
  provider: pypi
  user: __token__
  password: "$PYPI_TOKEN"
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$version = 3.6"
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: CTG+XvHwzZlUuc8Gdq96+sK9w1FbkRCBg0yiDGtXFVK8fWFPQEwxLBWQ+yL7vzkS1RMc+Ib7ML4tKU2CMlVxgATOT7RetOioFw56RyV/fd+9eon1PONuz+d5HTIHm64GMhKSxvC4TQbUA4m4+kRX8bCsCfUpTz90HpTm5nSXZ/o=
