language: python
sudo: false
cache: pip
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- python setup.py install
- pip install pyyaml
- pip install flask
- pip install six
- pip install pypandoc
- pip install coverage
- pip install codecov
# - sudo apt-get install -y pandoc
addons:
  apt_packages:
    - pandoc
before_script:
- mkdir prism
- mkdir prism/bin
- export PATH=$PATH:$PWD/prism/bin/
- ./test/prism.sh
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run unit2 discover; else coverage run -m unittest
  discover; fi
after_script:
- codecov
before_deploy:
- python ./register.py
deploy:
  provider: pypi
  user: thinkingserious
  password:
    secure: DoM21KiMKkt/7AS6zOqTs7j3fgInrpswRTPG3cqBNRSzyfkXeXmKecCPruooxvYKLM7fPNDOuIH2phgCjdx/XBtJwghNh34n+TzhNFEiI/6pV0iS4a9gW0+QU+GMYvQmfNlA9DKQ5N20FMy4XeK8QQFarJXQwW1/a5wWftbUYvQ=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.6'
notifications:
  hipchat:
    rooms:
      secure: Lo3L/YNWpn9ulGX4D2HlWrBOyxMPlLkFcwxbYViG69Ta6BV+c6YE+Pct43tExlL6sZ+nj5p8X4KRTeOM4sqASrebWA25nyUrNTm+vZYFbi5XfmGvvi8TEsgg0MYRQRWWn/R2z0kZW/fqOY6sqJuoIafMBmC3tayTJRiH1Ct2Cw0=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/sendgrid/%{repository}/commits/%{commit}">View on
      GitHub</a>'
    format: html
    notify: false
