dist: xenial # required for Python >= 3.7
language: python
cache: pip
services:
  - docker
env:
  matrix:
    - version=2.7
    - version=3.5
    - version=3.6
    - version=3.7
    - version=3.8
  global:
    - CC_TEST_REPORTER_ID=$TRAVIS_CODE_CLIMATE_TOKEN
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make test-docker
after_script:
  - make test-install
  - . venv/bin/activate; codecov
  - ./cc-test-reporter after-build --exit-code $?
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: env(version)=3.6

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: Yp7gJ6NPRPNgO77vwS0HynSdnU5LYlLlUNBEzcx+zy230UxuLLWcYZtIqsIqt4oZm45OwgJLBwoCMgmU2Jcj79rGyqWKYtUcLMLKgHVzSgxjm2outt2fxjXIJHIU60S3RCGofBJRkPwEMb7ibgwHYBEsH3wIeLrVVbWvimxka6A=
